### ISSUE TITLE
undefined, undefined

### ISSUE THREAD

**Issue by pqvst** [pqvst/cafeandcowork-test#6]
```
date: 2020-11-11
form:
  city: Foo
  name: Bar
  type: Cafe
  area: ""
  google_maps: ""
  address: ""
  station: ""
  hours: ""
  wifi: ""
  speed: ""
  power: ""
  vacancy: ""
  comfort: ""
  quiet: ""
  food: ""
  drinks: ""
  price: ""
  view: ""
  toilets: ""
  music: ""
  standing_tables: ""
  outdoor_seating: ""
  cash_only: ""
  animals: ""
  facebook: ""
  instagram: ""
  telephone: ""
  website: ""
  review: ""
  reviewer: ""

```
